[mypy]
exclude = vllmserver/_version\.py

[mypy-vllmserver._version]
ignore_missing_imports = True

[mypy-kserve.*]
ignore_missing_imports = True

[mypy-kserve_storage.*]
ignore_missing_imports = True

